---
title: "Project"
author: "anonymous"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r, warning=FALSE, results="hide", message=FALSE}
library(ggplot2)
library(posterior)
library(bayesplot)
library(rstan)
library(ggpubr)
library(tidyr)
library(dplyr)
library(ggcorrplot)
library(latex2exp)
library(gridExtra)
library(plyr)
library(loo)
library(invgamma)
```

```{r}
set.seed(123)

credit_risk <- read.csv(file="german_credit_data.csv")

summary(credit_risk)
```

```{r}
credit_risk <- subset(credit_risk, select=-c(`X`))
```

```{r}
miss <- function(x){sum(is.na(x))/length(x)*100}
apply(credit_risk, 2, miss)
```



```{r}
get_mode <- function(x) {
  ux <- unique(x)
  ux <- na.omit(ux)
  ux[which.max(tabulate(match(x, ux)))]
}

credit_risk$`Saving.accounts`[is.na(credit_risk$`Saving.accounts`)] <- get_mode(credit_risk$`Saving.accounts`)
credit_risk$`Checking.account`[is.na(credit_risk$`Checking.account`)] <- get_mode(credit_risk$`Checking.account`)

miss <- function(x){sum(is.na(x))/length(x)*100}
apply(credit_risk, 2, miss)
```

```{r}
ageplot <- ggplot(credit_risk, aes(x=Age, fill=Risk)) +
  labs(y="") +
  geom_histogram() + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```
```{r}
sexplot <- ggplot(credit_risk, aes(x=Sex, fill=Risk)) +
  labs(y="") +
  geom_bar()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```
```{r}
jobplot <- ggplot(credit_risk, aes(x=Job, fill=Risk)) +
  labs(y="") +
  geom_bar()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```
```{r}
housingplot <- ggplot(credit_risk, aes(x=Housing, fill=Risk)) +
  labs(y="") +
  geom_bar()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```

```{r}
savingplot <- ggplot(credit_risk, aes(x=Saving.accounts, fill=Risk)) +
  labs(y="") +
  geom_bar()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```
```{r}
credit_risk$Saving.accounts <- plyr::mapvalues(credit_risk$Saving.accounts, 
                                         from =c("little","moderate","quite rich","rich"), 
                                         to = c("little","moderate","rich","rich"))
```


```{r}
checking_plot <- ggplot(credit_risk, aes(x=Checking.account, fill=Risk)) +
  labs(y="") +
  geom_bar()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```

```{r}
credit_plot <- ggplot(credit_risk, aes(x=Credit.amount, fill=Risk)) +
  labs(y="") +
  geom_histogram()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```

```{r}
credit_risk <- credit_risk[credit_risk$Credit.amount < 10000,]
```

```{r}
duration <- ggplot(credit_risk, aes(x=Duration, fill=Risk)) +
  labs(y="") +
  geom_histogram()+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```

```{r}
credit_risk <- credit_risk[credit_risk$Duration < max(credit_risk$Duration),]
```

```{r}
purpose_plot <- ggplot(credit_risk, aes(x=Purpose, fill=Risk)) +
  labs(y="") +
  geom_bar() + 
  theme(axis.text.x=element_text(angle=40, hjust=1), legend.position="top")+ theme(axis.text=element_text(size=12),
        axis.title=element_text(size=20,face="bold"))
```

```{r}
credit_risk$Purpose <- plyr::mapvalues(credit_risk$Purpose,
                                       from = c("business","car","domestic appliances",
                                      "education","furniture/equipment","radio/TV","repairs","vacation/others"), 
                                      to = c("business","car","furniture/equipment","education",
                                             "furniture/equipment","radio/TV","others","others")) 
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.align='center', fig.height=6, fig.width=25}
ggarrange(ageplot, credit_plot, duration, ncol=3, common.legend=TRUE)
ggarrange(housingplot, jobplot, sexplot, ncol=3, common.legend=TRUE)
ggarrange(savingplot, checking_plot, ncol=2, common.legend=TRUE)
purpose_plot
```

```{r}
# Convert data into numerical data
credit_risk$Sex = as.numeric(factor(credit_risk$Sex))
credit_risk$Housing = as.numeric(factor(credit_risk$Housing))
credit_risk$Saving.accounts = as.numeric(factor(credit_risk$Saving.accounts))
credit_risk$Checking.account = as.numeric(factor(credit_risk$Checking.account))
credit_risk$Purpose = as.numeric(factor(credit_risk$Purpose))
credit_risk$Risk = as.numeric(factor(credit_risk$Risk)) - 1

ggcorrplot(cor(credit_risk), lab = TRUE, lab_size = 3)
```



```{r}
credit_risk <- credit_risk[sample(nrow(credit_risk)), ]
# Standardize data
data_pooled <- credit_risk %>% mutate_at(colnames(credit_risk)[!colnames(credit_risk) %in% c("Risk")], ~(scale(.) %>% as.vector))
data_hierarchical <- credit_risk %>% mutate_at(colnames(credit_risk)[!colnames(credit_risk) %in% c("Risk", "Purpose")], ~(scale(.) %>% as.vector))
```

```{r}
train_size <- round(nrow(data_pooled)/2, 0)
test_size <- nrow(data_pooled) - train_size
train_size/test_size
```

```{r}
data_train <- head(data_pooled, train_size)
data_test <- tail(data_pooled, test_size)

y_train_pooled = data_train$Risk
y_test_pooled = data_test$Risk

X_train_pooled = subset(data_train, select=-c(`Risk`)) 
X_test_pooled = subset(data_test, select=-c(`Risk`)) 

credit_data_pooled <- list(N_train=nrow(X_train_pooled), 
                            D=ncol(X_train_pooled), 
                            X_train=X_train_pooled, 
                            y_train=y_train_pooled,
                            N_test=nrow(X_test_pooled),
                            X_test=X_test_pooled)

pooled_fit <- stan(file="pooled.stan", data=credit_data_pooled, chains=4, iter=2000, warmup=1000)
```

```{r}
data_train <- head(data_hierarchical, train_size)
data_test <- tail(data_hierarchical, test_size)

y_train_hierarchical = data_train$Risk
y_test_hierarchical = data_test$Risk

X_train_hierarchical = subset(data_train, select=-c(`Risk`, `Purpose`)) 
X_test_hierarchical = subset(data_test, select=-c(`Risk`, `Purpose`)) 

ll_train = data_train$Purpose
ll_test = data_test$Purpose

credit_data_hierarchical <- list(N_train=nrow(X_train_hierarchical), 
                                  D=ncol(X_train_hierarchical), 
                                  L_train=length(unique(ll_train)),
                                  ll_train=ll_train,
                                  X_train=X_train_hierarchical, 
                                  y_train=y_train_hierarchical,
                                  N_test=nrow(X_test_hierarchical),
                                  L_test=length(unique(ll_test)),
                                  ll_test=ll_test,
                                  X_test=X_test_hierarchical)

hierarchical_fit <- stan(file="hierarchical.stan", data=credit_data_hierarchical, chains=4, iter=2000, warmup=1000)
```

Rhat
```{r}
r_hat = summary(pooled_fit)$summary[,"Rhat"]
ggplot(data=as.data.frame(r_hat)) +
  geom_histogram(aes(x=`r_hat`))
```

```{r}
r_hat = summary(hierarchical_fit)$summary[,"Rhat"]
ggplot(data=as.data.frame(r_hat)) +
  geom_histogram(aes(x=`r_hat`)) 
```

```{r}
mcmc_neff(neff_ratio(pooled_fit))

mcmc_neff(neff_ratio(hierarchical_fit))
```

```{r}
mcmc_nuts_divergence(nuts_params(hierarchical_fit), log_posterior(hierarchical_fit), chain = 4)
mcmc_nuts_divergence(nuts_params(pooled_fit), log_posterior(pooled_fit), chain = 4)
```


```{r}
pooled_loo <- loo(pooled_fit)
hierarchical_loo <- loo(hierarchical_fit)

ggplot() +
  geom_point(aes(x=1:length(hierarchical_loo$diagnostics$pareto_k), y=hierarchical_loo$diagnostics$pareto_k)) +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0), limits=c(min(0, min(hierarchical_loo$diagnostics$pareto_k)), 1), n.breaks=6) +
  geom_abline(slope=0, intercept=0.7, linetype="dashed", color="red") +
  geom_abline(slope=0, intercept=0.5, linetype="dashed", color="red") +
  labs(x="Data point", y="Pareto K value", title="Hierarchical model diagnostics") +
  theme(plot.title = element_text(hjust = 0.5)) 

ggplot() +
  geom_point(aes(x=1:length(pooled_loo$diagnostics$pareto_k), y=pooled_loo$diagnostics$pareto_k)) +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_y_continuous(expand = c(0, 0), limits=c(min(0, min(pooled_loo$diagnostics$pareto_k)), 1), n.breaks=6) +
  geom_abline(slope=0, intercept=0.7, linetype="dashed", color="red") +
  geom_abline(slope=0, intercept=0.5, linetype="dashed", color="red") +
  labs(x="Data point", y="Pareto K value", title="Non hierarchical model diagnostics") +
  theme(plot.title = element_text(hjust = 0.5)) 
```

```{r}
loo_compare(pooled_loo, hierarchical_loo)
```

Posterior predictive check
```{r}
# Extract fit
ypred_pooled <- as.matrix(pooled_fit, pars="y_pred")
ypred_hierarchical <- as.matrix(hierarchical_fit, pars="y_pred")

ppc_dens_overlay(y_test_pooled, ypred_pooled[1:50, ])
ppc_hist(y_test_pooled, ypred_pooled[1:5, ])

ppc_dens_overlay(y_test_hierarchical, ypred_hierarchical[1:50, ])
ppc_hist(y_test_hierarchical, ypred_hierarchical[1:5, ])
```

```{r}
confusion_matrix <- function(predictions, actual) {
  true_pos_count <- 0
  true_neg_count <- 0
  false_neg_count <- 0
  false_pos_count <- 0
  for(i in 1:ncol(predictions)) {
    label = paste(c("y_pred[",i,"]"), collapse="")
    predict = mean(predictions[ , label])
    if(predict >= 0.5 && actual[i] == 1) 
      true_pos_count <- true_pos_count + 1 
    else if(predict >= 0.5 && actual[i] == 0) 
      false_pos_count <- false_pos_count + 1
    else if(predict < 0.5 && actual[i] == 0) 
      true_neg_count <- true_neg_count + 1 
    else if(predict < 0.5 && actual[i] == 1) 
      false_neg_count <- false_neg_count + 1 
  }
  matrix(c(true_pos_count, false_pos_count, false_neg_count, true_neg_count), nrow=2, dimnames=list(c("Predicted True", "Predicted False"), c("Actual True", "Actual False")))
}

pooled_conf_mat <- confusion_matrix(ypred_pooled, y_test_pooled)
hierarchical_conf_mat <- confusion_matrix(ypred_hierarchical, y_test_hierarchical)

pooled_conf_mat
hierarchical_conf_mat
```

Accuracy
```{r}
(pooled_conf_mat[1,1] + pooled_conf_mat[2, 2]) / 
  (pooled_conf_mat[1,1] + pooled_conf_mat[2, 2] + pooled_conf_mat[1,2] + pooled_conf_mat[2, 1])

(hierarchical_conf_mat[1,1] + hierarchical_conf_mat[2, 2]) / 
  (hierarchical_conf_mat[1,1] + hierarchical_conf_mat[2, 2] + hierarchical_conf_mat[1,2] + hierarchical_conf_mat[2, 1])
```

False negative
```{r}
pooled_conf_mat[2,1]/ 
  (pooled_conf_mat[1, 1] + pooled_conf_mat[2,1])

hierarchical_conf_mat[2,1]/ 
  (hierarchical_conf_mat[1, 1] + hierarchical_conf_mat[2,1])
```

# prior check

```{r}
prior_pooled_fit <- stan(file="prior_check_pooled.stan", data=credit_data_pooled, chains=4, iter=2000, warmup=1000)
```

```{r}
prior_hierarchical_fit <- stan(file="prior_check_hierarchical.stan", data=credit_data_hierarchical, chains=4, iter=2000, warmup=1000)
```

```{r}
current_pooled_draws <- as_draws_df(pooled_fit)
prior_pooled_draws <- as_draws_df(prior_pooled_fit)

current_pooled_posterior <- as_tibble(current_pooled_draws$`beta_0`)
prior_pooled_posterior <- as_tibble(prior_pooled_draws$`beta_0`)

scale=seq(-5, 5.5, by=0.1)
       
current_pooled_prior <- tibble(x=scale, y=dnorm(scale, mean=0, sd=1))
tested_pooled_prior <- tibble(x=scale, y=dnorm(scale, mean=2, sd=0.3))

pooled_prior_comp <- ggplot() +
  geom_line(data=current_pooled_prior, aes(x=x, y=y)) +
  geom_area(data=current_pooled_prior, aes(x=x, y=y, fill="Original prior"), alpha=0.5) +
  geom_line(data=tested_pooled_prior, aes(x=x, y=y)) +
  geom_area(data=tested_pooled_prior, aes(x=x, y=y, fill="Alternative prior"), alpha=0.5) +
  scale_fill_manual(name="Priors", breaks=c("Original prior", "Alternative prior"), values=c("lightblue", "dodgerblue3")) +
  labs(x="beta_0", y="density") 
  

pooled_posterior_comp <- ggplot() +
  geom_density(data=current_pooled_posterior, aes(x=value, fill="Original prior"), alpha=0.5) +
  geom_density(data=prior_pooled_posterior, aes(x=value, fill="Alternative prior"), alpha=0.5) +
  scale_fill_manual(name="Priors", breaks=c("Original prior", "Alternative prior"), values=c("lightblue", "dodgerblue3")) +
  labs(x="beta_0 (Posterior)", y="density") 

ggarrange(pooled_prior_comp, pooled_posterior_comp, ncol=2, common.legend=TRUE)
```

```{r}
prior_pooled_loo <- loo(prior_pooled_fit)
loo_compare(pooled_loo, prior_pooled_loo)
```

```{r, warning=FALSE}
current_hierarchical_draws <- as_draws_df(hierarchical_fit)
prior_hierarchical_draws <- as_draws_df(prior_hierarchical_fit)

current_hierarchical_posterior <- as_tibble(current_hierarchical_draws$`beta_0[1]`)
prior_hierarchical_posterior <- as_tibble(prior_hierarchical_draws$`beta_0[1]`)

scale <- seq(-5, 5.5, by=0.1)
       
current_hierarchical_prior_mu <- tibble(x=scale, y=dnorm(scale, mean=0, sd=1))
tested_hierarchical_prior_mu <- tibble(x=scale, y=dnorm(scale, mean=2, sd=0.3))

current_hierarchical_prior_sigma <- tibble(x=scale, y=dnorm(scale, mean=0, sd=1))
tested_hierarchical_prior_sigma <- tibble(x=scale, y=dnorm(scale, mean=2, sd=0.5))

hierarchical_prior_comp_mu <- ggplot() +
  geom_line(data=current_hierarchical_prior_mu, aes(x=x, y=y)) +
  geom_area(data=current_hierarchical_prior_mu, aes(x=x, y=y, fill="Original prior"), alpha=0.5) +
  geom_line(data=tested_hierarchical_prior_mu, aes(x=x, y=y)) +
  geom_area(data=tested_hierarchical_prior_mu, aes(x=x, y=y, fill="Alternative prior"), alpha=0.5) +
  scale_fill_manual(name="Priors", breaks=c("Original prior", "Alternative prior"), values=c("lightblue", "dodgerblue3")) +
  labs(x="mu_0", y="density") 

scale <- seq(0, 6.5, by=0.1)

current_hierarchical_prior_sigma <- data_frame(x=scale, y=dinvgamma(scale, shape=0.5, rate=1))
tested_hierarchical_prior_sigma <- data_frame(x=scale, y=dinvgamma(scale, shape=1, rate=0.1))

hierarchical_prior_comp_sigma <- ggplot() +
  geom_line(data=current_hierarchical_prior_sigma, aes(x=x, y=y)) +
  geom_area(data=current_hierarchical_prior_sigma, aes(x=x, y=y, fill="Original prior"), alpha=0.5) + 
  geom_line(data=tested_hierarchical_prior_sigma, aes(x=x, y=y)) +
  geom_area(data=tested_hierarchical_prior_sigma, aes(x=x, y=y, fill="Alternative prior"), alpha=0.5) +
  scale_fill_manual(name="Priors", breaks=c("Original prior", "Alternative prior"), values=c("lightblue", "dodgerblue3")) +
  labs(x="sigma_0", y="density") 

posterior_comp <- ggplot() +
  geom_density(data=current_hierarchical_posterior, aes(x=value, fill="Original prior"), alpha=0.5) +
  geom_density(data=prior_hierarchical_posterior, aes(x=value, fill="Alternative prior"), alpha=0.5) +
  scale_fill_manual(name="Priors", breaks=c("Original prior", "Alternative prior"), values=c("lightblue", "dodgerblue3")) +
  labs(x="beta_0_1 (Posterior)", y="density") 

ggarrange(hierarchical_prior_comp_mu, hierarchical_prior_comp_sigma, posterior_comp, ncol=3, common.legend=TRUE)
```













