---
title: "Project"
author: "anonymous"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r, warning=FALSE, results="hide", message=FALSE}
library(ggplot2)
library(posterior)
library(bayesplot)
library(rstan)
library(tidyr)
library(dplyr)
library(ggcorrplot)
library(plyr)
library(loo)
```

```{r}
set.seed(123)

credit_risk <- read.csv(file="german_credit_data.csv")

summary(credit_risk)
```

```{r}
credit_risk <- subset(credit_risk, select=-c(`X`))
```

```{r}
miss <- function(x){sum(is.na(x))/length(x)*100}
apply(credit_risk, 2, miss)
```



```{r}
get_mode <- function(x) {
  ux <- unique(x)
  ux <- na.omit(ux)
  ux[which.max(tabulate(match(x, ux)))]
}

credit_risk$`Saving.accounts`[is.na(credit_risk$`Saving.accounts`)] <- get_mode(credit_risk$`Saving.accounts`)
credit_risk$`Checking.account`[is.na(credit_risk$`Checking.account`)] <- get_mode(credit_risk$`Checking.account`)

miss <- function(x){sum(is.na(x))/length(x)*100}
apply(credit_risk, 2, miss)
```

```{r}
ggplot(credit_risk, aes(x=Age, fill=Risk)) +
  geom_bar()
```
```{r}
ggplot(credit_risk, aes(x=Sex, fill=Risk)) +
  geom_bar()
```
```{r}
ggplot(credit_risk, aes(x=Job, fill=Risk)) +
  geom_bar()
```
```{r}
ggplot(credit_risk, aes(x=Housing, fill=Risk)) +
  geom_bar()
```

```{r}
ggplot(credit_risk, aes(x=Saving.accounts, fill=Risk)) +
  geom_bar()
```
```{r}
credit_risk$Saving.accounts <- plyr::mapvalues(credit_risk$Saving.accounts, 
                                         from =c("little","moderate","quite rich","rich"), 
                                         to = c("little","moderate","rich","rich"))
```

```{r}
ggplot(credit_risk, aes(x=Saving.accounts, fill=Risk)) +
  geom_bar()
```


```{r}
ggplot(credit_risk, aes(x=Checking.account, fill=Risk)) +
  geom_bar()
```

```{r}
ggplot(credit_risk, aes(x=Credit.amount, fill=Risk)) +
  geom_bar()
```

```{r}
credit_risk <- credit_risk[credit_risk$Credit.amount < 10000,]
```

```{r}
ggplot(credit_risk, aes(x=Credit.amount, fill=Risk)) +
  geom_bar()
```

```{r}
ggplot(credit_risk, aes(x=Duration, fill=Risk)) +
  geom_bar()
```

```{r}
ggplot(credit_risk, aes(x=Purpose, fill=Risk)) +
  geom_bar()
```

```{r}
credit_risk$Purpose <- plyr::mapvalues(credit_risk$Purpose,
                                       from = c("business","car","domestic appliances",
                                      "education","furniture/equipment","radio/TV","repairs","vacation/others"), 
                                      to = c("business","car","furniture/equipment","education",
                                             "furniture/equipment","radio/TV","others","others")) 
```

```{r}
ggplot(credit_risk, aes(x=Purpose, fill=Risk)) +
  geom_bar()
```

```{r}
# Convert data into numerical data
credit_risk$Sex = as.numeric(factor(credit_risk$Sex))
credit_risk$Housing = as.numeric(factor(credit_risk$Housing))
credit_risk$Saving.accounts = as.numeric(factor(credit_risk$Saving.accounts))
credit_risk$Checking.account = as.numeric(factor(credit_risk$Checking.account))
credit_risk$Purpose = as.numeric(factor(credit_risk$Purpose))
credit_risk$Risk = as.numeric(factor(credit_risk$Risk)) - 1

ggcorrplot(cor(credit_risk), lab = TRUE, lab_size = 3)
```

```{r}
ggplot(credit_risk, aes(x=Duration, y=Credit.amount)) +
  geom_point() +
  geom_smooth(method="lm")
```



```{r}
# Standardize data
credit_risk_hie <- credit_risk %>% mutate_at(colnames(credit_risk)[!colnames(credit_risk) %in% c("Risk", "Purpose")], ~(scale(.) %>% as.vector))

credit_risk_non_hie <- credit_risk %>% mutate_at(colnames(credit_risk)[!colnames(credit_risk) %in% c("Risk")], ~(scale(.) %>% as.vector))
```

```{r}
credit_risk_train <- head(credit_risk_non_hie, 500)
credit_risk_test <- tail(credit_risk_non_hie, 500)

y_train = credit_risk_train$Risk
y_test = credit_risk_test$Risk

X_train = subset(credit_risk_train, select=-c(`Risk`)) 
X_test = subset(credit_risk_test, select=-c(`Risk`)) 

credit_data <- list(N_train=nrow(X_train), 
                    D=ncol(X_train), 
                    X_train=X_train, 
                    y_train=y_train,
                    N_test=nrow(X_test),
                    X_test=X_test)

non_hierarchical_fit <- stan(file="non-hierarchical.stan", data=credit_data, chains=4, iter=2000, warmup=1000)
```

```{r}
credit_risk_train <- head(credit_risk_hie, 500)
credit_risk_test <- tail(credit_risk_hie, 500)

y_train = credit_risk_train$Risk
y_test = credit_risk_test$Risk

X_train = subset(credit_risk_train, select=-c(`Risk`, `Purpose`)) 
X_test = subset(credit_risk_test, select=-c(`Risk`, `Purpose`)) 

ll_train = credit_risk_train$Purpose
ll_test = credit_risk_test$Purpose

credit_data <- list(N_train=nrow(X_train), 
                    D=ncol(X_train), 
                    L_train=length(unique(ll_train)),
                    ll_train=ll_train,
                    X_train=X_train, 
                    y_train=y_train,
                    N_test=nrow(X_test),
                    L_test=length(unique(ll_test)),
                    ll_test=ll_test,
                    X_test=X_test)

hierarchical_fit <- stan(file="hierarchical.stan", data=credit_data, chains=1, iter=1000, warmup=500)
```

```{r}
print(hierarchical_fit)
```


Rhat
```{r}
r_hat = summary(non_hierarchical_fit)$summary[,"Rhat"]
ggplot(data=as.data.frame(r_hat)) +
  geom_histogram(aes(x=`r_hat`))
```

```{r}
mcmc_neff(neff_ratio(non_hierarchical_fit))

mcmc_neff(neff_ratio(hierarchical_fit))
```

```{r}
r_hat = summary(hierarchical_fit)$summary[,"Rhat"]
ggplot(data=as.data.frame(r_hat)) +
  geom_histogram(aes(x=`r_hat`))
```

Posterior predictive check
```{r}
# Extract fit
ypred <- as.matrix(non_hierarchical_fit, pars="y_pred")
ypred_hie <- as.matrix(hierarchical_fit, pars="y_pred")

ppc_dens_overlay(y_test, ypred[1:50, ])
ppc_hist(y_test, ypred[1:5, ])

ppc_dens_overlay(y_test, ypred_hie[1:50, ])
ppc_hist(y_test, ypred_hie[1:5, ])
```




